#!/bin/sh
#
# usbipd    Starts USB/IP daemon.
#

DAEMON=/usr/sbin/usbipd
PIDFILE=/var/run/usbipd.pid

[ -f $DAEMON ] || exit 0

start() {
	printf "Starting usbipd: "
start-stop-daemon -S -q -b -m -p $PIDFILE -x $DAEMON -- -D
	echo "OK"
}

stop() {
	printf "Stopping usbipd: "
	start-stop-daemon -K -q -p $PIDFILE
	rm -f $PIDFILE
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
