#!/bin/sh
#
# tailscale    Starts Tailscale VPN daemon.
#

DAEMON=/usr/sbin/tailscaled
PIDFILE=/var/run/tailscaled.pid
STATE_DIR=/userdata/tailscale

[ -f $DAEMON ] || exit 0

start() {
	mkdir -p $STATE_DIR
	printf "Starting tailscaled: "
	start-stop-daemon -S -q -b -m -p $PIDFILE -x $DAEMON -- \
		--state=$STATE_DIR/tailscaled.state \
		--statedir=$STATE_DIR \
		--tun=tailscale0
	echo "OK"
}

stop() {
	printf "Stopping tailscaled: "
	start-stop-daemon -K -q -p $PIDFILE
	rm -f $PIDFILE
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
