#!/bin/sh
#
# uipm    Starts UI Package Manager web interface.
#

DAEMON=/opt/uipm/uipm
PIDFILE=/var/run/uipm.pid
DAEMON_ARGS="-addr :80 -dir /opt/uipm/dist -config /etc/uipm/config.json"

[ -f $DAEMON ] || exit 0

start() {
	printf "Starting uipm: "
	start-stop-daemon -S -q -b -m -p $PIDFILE -x $DAEMON -- $DAEMON_ARGS
	echo "OK"
}

stop() {
	printf "Stopping uipm: "
	start-stop-daemon -K -q -p $PIDFILE
	rm -f $PIDFILE
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
